name: Frontend
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - "${VITE_FRONTEND_PORT}:${VITE_FRONTEND_PORT}"      # Vite’s default dev port
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "${VITE_FRONTEND_PORT}"]
    env_file:
      - .env
